In [1]:
import gensim
from gensim import corpora
from gensim.models import LdaModel
from gensim.models.ldamulticore import LdaMulticore
from gensim.utils import simple_preprocess
from nltk.corpus import stopwords
import pandas as pd

# Example function for text preprocessing
def preprocess_text(text):
    stop_words = set(stopwords.words('english'))
    tokens = simple_preprocess(text)
    tokens = [token for token in tokens if token not in stop_words]
    return tokens

# Load central bank speeches data
# Replace 'your_speeches.csv' with the path to your CSV file containing speeches
speeches_df = pd.read_excel('FEDdatasentiment222.xlsx')

# Preprocess speeches
speeches_df['processed_text'] = speeches_df['text'].apply(preprocess_text)

# Create dictionary and corpus
dictionary = corpora.Dictionary(speeches_df['processed_text'])
corpus = [dictionary.doc2bow(text) for text in speeches_df['processed_text']]

# Train LDA model
lda_model = LdaMulticore(corpus=corpus,
                          id2word=dictionary,
                          num_topics=20, # Adjust based on your expectation of the number of topics
                          workers=4,
                          passes=10)

# Function to get topic distribution for a speech
def get_topic_distribution(text):
    bow = dictionary.doc2bow(preprocess_text(text))
    topic_distribution = lda_model.get_document_topics(bow)
    return topic_distribution

C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
# Print the topics and associated words
topics = lda_model.print_topics(num_words=10)  # Adjust the number of words shown as needed

for topic in topics:
    print(topic)

(0, '0.044*"bank" + 0.021*"community" + 0.011*"banking" + 0.008*"regulatory" + 0.008*"regulation" + 0.007*"federal" + 0.007*"supervisory" + 0.006*"supervision" + 0.006*"area" + 0.006*"risk"')
(1, '0.024*"inflation" + 0.014*"rate" + 0.011*"percent" + 0.010*"price" + 0.010*"year" + 0.009*"policy" + 0.009*"labor" + 0.009*"growth" + 0.008*"economy" + 0.007*"economic"')
(2, '0.027*"risk" + 0.017*"bank" + 0.017*"basel" + 0.014*"capital" + 0.012*"ii" + 0.011*"management" + 0.008*"institution" + 0.008*"banking" + 0.006*"organization" + 0.006*"market"')
(3, '0.021*"financial" + 0.016*"country" + 0.013*"market" + 0.013*"capital" + 0.008*"risk" + 0.007*"bank" + 0.007*"growth" + 0.007*"institution" + 0.006*"economy" + 0.006*"system"')
(4, '0.010*"community" + 0.010*"market" + 0.010*"housing" + 0.008*"property" + 0.008*"neighborhood" + 0.007*"development" + 0.007*"financial" + 0.007*"data" + 0.006*"return" + 0.006*"foreclosure"')
(5, '0.037*"bank" + 0.026*"community" + 0.015*"business" + 0.015*"small" + 0.014*"loan" + 0.011*"lending" + 0.011*"federal" + 0.009*"reserve" + 0.009*"credit" + 0.008*"institution"')
(6, '0.015*"reserve" + 0.015*"federal" + 0.012*"bank" + 0.010*"fed" + 0.009*"policy" + 0.008*"monetary" + 0.008*"central" + 0.007*"crisis" + 0.007*"independence" + 0.006*"board"')
(7, '0.022*"bank" + 0.018*"liquidity" + 0.017*"dollar" + 0.009*"market" + 0.007*"funding" + 0.007*"asset" + 0.007*"lcr" + 0.007*"international" + 0.006*"cbdc" + 0.006*"financial"')
(8, '0.025*"rate" + 0.019*"policy" + 0.012*"inflation" + 0.011*"interest" + 0.011*"monetary" + 0.011*"federal" + 0.010*"price" + 0.009*"financial" + 0.009*"market" + 0.008*"reserve"')
(9, '0.022*"financial" + 0.014*"bank" + 0.013*"risk" + 0.012*"capital" + 0.011*"firm" + 0.008*"system" + 0.008*"market" + 0.007*"would" + 0.006*"banking" + 0.006*"stress"')
(10, '0.021*"clearing" + 0.013*"technology" + 0.012*"ledger" + 0.011*"settlement" + 0.009*"distributed" + 0.009*"market" + 0.008*"financial" + 0.008*"new" + 0.007*"clearinghouses" + 0.006*"ccp"')
(11, '0.028*"payment" + 0.017*"bank" + 0.014*"system" + 0.014*"financial" + 0.012*"federal" + 0.011*"reserve" + 0.010*"service" + 0.010*"consumer" + 0.008*"innovation" + 0.007*"new"')
(12, '0.023*"community" + 0.021*"bank" + 0.013*"reserve" + 0.012*"federal" + 0.009*"financial" + 0.006*"text" + 0.006*"business" + 0.006*"return" + 0.006*"economic" + 0.005*"system"')
(13, '0.027*"market" + 0.022*"bank" + 0.016*"financial" + 0.016*"reserve" + 0.015*"federal" + 0.013*"liquidity" + 0.011*"credit" + 0.007*"fund" + 0.007*"treasury" + 0.007*"security"')
(14, '0.013*"united" + 0.012*"state" + 0.009*"return" + 0.009*"position" + 0.009*"investment" + 0.009*"liability" + 0.008*"net" + 0.008*"claim" + 0.005*"financial" + 0.005*"account"')
(15, '0.032*"policy" + 0.023*"monetary" + 0.012*"rate" + 0.011*"inflation" + 0.010*"economy" + 0.010*"federal" + 0.010*"central" + 0.009*"bank" + 0.008*"economic" + 0.008*"reserve"')
(16, '0.030*"mortgage" + 0.016*"loan" + 0.016*"consumer" + 0.015*"credit" + 0.011*"borrower" + 0.009*"market" + 0.008*"federal" + 0.008*"lender" + 0.007*"subprime" + 0.007*"housing"')
(17, '0.018*"market" + 0.015*"financial" + 0.009*"economic" + 0.007*"federal" + 0.007*"economy" + 0.007*"rate" + 0.007*"credit" + 0.006*"business" + 0.005*"household" + 0.005*"reserve"')
(18, '0.022*"policy" + 0.017*"federal" + 0.017*"rate" + 0.013*"reserve" + 0.012*"fomc" + 0.011*"committee" + 0.011*"inflation" + 0.010*"monetary" + 0.009*"percent" + 0.008*"return"')
(19, '0.014*"economic" + 0.010*"return" + 0.009*"percent" + 0.009*"education" + 0.008*"text" + 0.008*"income" + 0.008*"growth" + 0.007*"research" + 0.007*"worker" + 0.007*"productivity"')

In [3]:
# Print topics identified by LDA model
for topic_idx, topic in lda_model.print_topics():
    print(topic)
    print()
#don't need 2, 5, 9, 11, 15, 16, 18

0.044*"bank" + 0.021*"community" + 0.011*"banking" + 0.008*"regulatory" + 0.008*"regulation" + 0.007*"federal" + 0.007*"supervisory" + 0.006*"supervision" + 0.006*"area" + 0.006*"risk"

0.024*"inflation" + 0.014*"rate" + 0.011*"percent" + 0.010*"price" + 0.010*"year" + 0.009*"policy" + 0.009*"labor" + 0.009*"growth" + 0.008*"economy" + 0.007*"economic"

0.027*"risk" + 0.017*"bank" + 0.017*"basel" + 0.014*"capital" + 0.012*"ii" + 0.011*"management" + 0.008*"institution" + 0.008*"banking" + 0.006*"organization" + 0.006*"market"

0.021*"financial" + 0.016*"country" + 0.013*"market" + 0.013*"capital" + 0.008*"risk" + 0.007*"bank" + 0.007*"growth" + 0.007*"institution" + 0.006*"economy" + 0.006*"system"

0.010*"community" + 0.010*"market" + 0.010*"housing" + 0.008*"property" + 0.008*"neighborhood" + 0.007*"development" + 0.007*"financial" + 0.007*"data" + 0.006*"return" + 0.006*"foreclosure"

0.037*"bank" + 0.026*"community" + 0.015*"business" + 0.015*"small" + 0.014*"loan" + 0.011*"lending" + 0.011*"federal" + 0.009*"reserve" + 0.009*"credit" + 0.008*"institution"

0.015*"reserve" + 0.015*"federal" + 0.012*"bank" + 0.010*"fed" + 0.009*"policy" + 0.008*"monetary" + 0.008*"central" + 0.007*"crisis" + 0.007*"independence" + 0.006*"board"

0.022*"bank" + 0.018*"liquidity" + 0.017*"dollar" + 0.009*"market" + 0.007*"funding" + 0.007*"asset" + 0.007*"lcr" + 0.007*"international" + 0.006*"cbdc" + 0.006*"financial"

0.025*"rate" + 0.019*"policy" + 0.012*"inflation" + 0.011*"interest" + 0.011*"monetary" + 0.011*"federal" + 0.010*"price" + 0.009*"financial" + 0.009*"market" + 0.008*"reserve"

0.022*"financial" + 0.014*"bank" + 0.013*"risk" + 0.012*"capital" + 0.011*"firm" + 0.008*"system" + 0.008*"market" + 0.007*"would" + 0.006*"banking" + 0.006*"stress"

0.021*"clearing" + 0.013*"technology" + 0.012*"ledger" + 0.011*"settlement" + 0.009*"distributed" + 0.009*"market" + 0.008*"financial" + 0.008*"new" + 0.007*"clearinghouses" + 0.006*"ccp"

0.028*"payment" + 0.017*"bank" + 0.014*"system" + 0.014*"financial" + 0.012*"federal" + 0.011*"reserve" + 0.010*"service" + 0.010*"consumer" + 0.008*"innovation" + 0.007*"new"

0.023*"community" + 0.021*"bank" + 0.013*"reserve" + 0.012*"federal" + 0.009*"financial" + 0.006*"text" + 0.006*"business" + 0.006*"return" + 0.006*"economic" + 0.005*"system"

0.027*"market" + 0.022*"bank" + 0.016*"financial" + 0.016*"reserve" + 0.015*"federal" + 0.013*"liquidity" + 0.011*"credit" + 0.007*"fund" + 0.007*"treasury" + 0.007*"security"

0.013*"united" + 0.012*"state" + 0.009*"return" + 0.009*"position" + 0.009*"investment" + 0.009*"liability" + 0.008*"net" + 0.008*"claim" + 0.005*"financial" + 0.005*"account"

0.032*"policy" + 0.023*"monetary" + 0.012*"rate" + 0.011*"inflation" + 0.010*"economy" + 0.010*"federal" + 0.010*"central" + 0.009*"bank" + 0.008*"economic" + 0.008*"reserve"

0.030*"mortgage" + 0.016*"loan" + 0.016*"consumer" + 0.015*"credit" + 0.011*"borrower" + 0.009*"market" + 0.008*"federal" + 0.008*"lender" + 0.007*"subprime" + 0.007*"housing"

0.018*"market" + 0.015*"financial" + 0.009*"economic" + 0.007*"federal" + 0.007*"economy" + 0.007*"rate" + 0.007*"credit" + 0.006*"business" + 0.005*"household" + 0.005*"reserve"

0.022*"policy" + 0.017*"federal" + 0.017*"rate" + 0.013*"reserve" + 0.012*"fomc" + 0.011*"committee" + 0.011*"inflation" + 0.010*"monetary" + 0.009*"percent" + 0.008*"return"

0.014*"economic" + 0.010*"return" + 0.009*"percent" + 0.009*"education" + 0.008*"text" + 0.008*"income" + 0.008*"growth" + 0.007*"research" + 0.007*"worker" + 0.007*"productivity"

In [4]:
#don't need 2, 5, 9, 11, 15, 16, 18
# Define topics of interest
topics_of_interest = ['economic growth', 'monetary policy', 'financial risk', 'inflation', 'global economy', 'inflation and market', 'economic policy', 'monetary policy and interest rates', 'economic growth and trade', 'monetary policy and global economy', 'economic policy and inflation', 'monetary policy and climate change', 'financial market and asset prices'] # Adjust as needed

# Filter speeches based on topics of interest
relevant_speeches = []
for idx, speech in speeches_df.iterrows():
    topic_distribution = get_topic_distribution(speech['text'])
    # Check if any of the topics of interest have significant probability in the topic distribution
    for topic, prob in topic_distribution:
        if lda_model.print_topic(topic) in topics_of_interest and prob > 0.2: # Adjust probability threshold as needed
            relevant_speeches.append(speech)
            break

# Now relevant_speeches contains the filtered speeches that match the topics of interest

In [5]:
print(relevant_speeches)

[]

In [6]:
# Filter speeches based on topics of interest directly from DataFrame
topics_of_interest = [2, 5, 9] # Adjust as needed

relevant_speeches_df = pd.DataFrame(columns=speeches_df.columns)  # Create an empty DataFrame with the same columns as speeches_df

for idx, speech in speeches_df.iterrows():
    topic_distribution = get_topic_distribution(speech['text'])
    # Check if any of the topics of interest have significant probability in the topic distribution
    for topic, prob in topic_distribution:
        if lda_model.print_topic(topic) in topics_of_interest and prob > 0.2: # Adjust probability threshold as needed
            relevant_speeches_df = relevant_speeches_df.append(speech, ignore_index=True)
            break

# Now relevant_speeches_df contains only the relevant speeches

In [9]:
relevant_speeches_df.head()

Empty DataFrame
Columns: [Unnamed: 0.2, Unnamed: 0.1, Unnamed: 0, Link URL, Author, date, Title, text, sentiment vader, vader_sentiment, positive_score, negative_score, uncertainty_score, Polarity_Score, processed_text]
Index: []

In [10]:
for idx, speech in speeches_df.iterrows():
    topic_distribution = get_topic_distribution(speech['text'])
    print(f"Speech {idx} - Topic Distribution: {topic_distribution}")

Speech 0 - Topic Distribution: [(1, 0.7445404), (4, 0.018798122), (11, 0.14834422), (19, 0.08775077)]
Speech 1 - Topic Distribution: [(2, 0.8607483), (16, 0.13825937)]
Speech 2 - Topic Distribution: [(5, 0.21194439), (6, 0.41135848), (12, 0.31939813), (17, 0.05440221)]
Speech 3 - Topic Distribution: [(2, 0.044782463), (3, 0.16577283), (8, 0.06434845), (9, 0.5779154), (12, 0.11295422), (17, 0.03095386)]
Speech 4 - Topic Distribution: [(8, 0.012105646), (19, 0.98731583)]
Speech 5 - Topic Distribution: [(1, 0.7396689), (8, 0.24934733), (17, 0.010579843)]
Speech 6 - Topic Distribution: [(0, 0.4189778), (1, 0.041250106), (2, 0.071567014), (5, 0.35912457), (9, 0.03861317), (17, 0.062864505)]
Speech 7 - Topic Distribution: [(0, 0.027069058), (2, 0.16867462), (3, 0.4714422), (9, 0.2976105), (12, 0.034387555)]
Speech 8 - Topic Distribution: [(3, 0.03961365), (5, 0.03144069), (9, 0.32375538), (11, 0.033950314), (12, 0.2526618), (13, 0.27334794), (16, 0.039684553)]
Speech 9 - Topic Distribution: [(8, 0.9030113), (9, 0.08051824), (17, 0.016132439)]
Speech 10 - Topic Distribution: [(8, 0.990007)]
Speech 11 - Topic Distribution: [(2, 0.99956185)]
Speech 12 - Topic Distribution: [(2, 0.976705), (16, 0.022862582)]
Speech 13 - Topic Distribution: [(9, 0.51733965), (10, 0.4664725), (15, 0.012672422)]
Speech 14 - Topic Distribution: [(6, 0.06143145), (12, 0.5668176), (16, 0.09766654), (19, 0.27158886)]
Speech 15 - Topic Distribution: [(3, 0.17426975), (8, 0.07060129), (9, 0.05228126), (12, 0.5758805), (19, 0.1255047)]
Speech 16 - Topic Distribution: [(2, 0.9929955)]
Speech 17 - Topic Distribution: [(1, 0.99864686)]
Speech 18 - Topic Distribution: [(2, 0.060439505), (8, 0.29376128), (9, 0.22628605), (11, 0.033767454), (13, 0.085324146), (17, 0.2929193)]
Speech 19 - Topic Distribution: [(3, 0.022840373), (4, 0.885046), (12, 0.08986715)]
Speech 20 - Topic Distribution: [(1, 0.68248445), (3, 0.1072346), (9, 0.025307849), (17, 0.18445143)]
Speech 21 - Topic Distribution: [(2, 0.5345844), (9, 0.3743075), (11, 0.09066812)]
Speech 22 - Topic Distribution: [(4, 0.66436017), (12, 0.2840301), (19, 0.050936557)]
Speech 23 - Topic Distribution: [(2, 0.79544634), (5, 0.028465696), (9, 0.04037001), (13, 0.014201655), (16, 0.1086944)]
Speech 24 - Topic Distribution: [(11, 0.9988193)]
Speech 25 - Topic Distribution: [(2, 0.05398417), (9, 0.84583), (13, 0.09967175)]
Speech 26 - Topic Distribution: [(2, 0.011485953), (4, 0.018059025), (8, 0.046933804), (9, 0.5079581), (11, 0.013821697), (13, 0.22632366), (17, 0.17509706)]
Speech 27 - Topic Distribution: [(1, 0.091003634), (4, 0.5989372), (11, 0.050228335), (19, 0.24528229)]
Speech 28 - Topic Distribution: [(1, 0.05171641), (4, 0.8729408), (12, 0.06938506)]
Speech 29 - Topic Distribution: [(1, 0.97071433), (3, 0.020846995)]
Speech 30 - Topic Distribution: [(2, 0.8775426), (5, 0.042096704), (9, 0.044106998), (12, 0.035825085)]
Speech 31 - Topic Distribution: [(6, 0.08281924), (13, 0.03415496), (16, 0.21631093), (19, 0.66583014)]
Speech 32 - Topic Distribution: [(2, 0.52468616), (9, 0.37866879), (11, 0.09621639)]
Speech 33 - Topic Distribution: [(4, 0.26999328), (11, 0.06940895), (12, 0.11153471), (16, 0.28646725), (19, 0.25895712)]
Speech 34 - Topic Distribution: [(1, 0.14826663), (2, 0.37251842), (16, 0.4066699), (17, 0.07216839)]
Speech 35 - Topic Distribution: [(1, 0.90621847), (3, 0.042343363), (19, 0.050916236)]
Speech 36 - Topic Distribution: [(3, 0.100486174), (8, 0.8902666)]
Speech 37 - Topic Distribution: [(2, 0.9995598)]
Speech 38 - Topic Distribution: [(1, 0.406553), (3, 0.32773438), (8, 0.1652895), (17, 0.031227747), (19, 0.06885203)]
Speech 39 - Topic Distribution: [(1, 0.08725747), (8, 0.014351124), (9, 0.14736743), (17, 0.73308384), (19, 0.017493088)]
Speech 40 - Topic Distribution: [(1, 0.015369601), (3, 0.4784503), (19, 0.5056631)]
Speech 41 - Topic Distribution: [(1, 0.23999104), (13, 0.11802659), (19, 0.6389001)]
Speech 42 - Topic Distribution: [(2, 0.31495872), (6, 0.20397107), (12, 0.17516606), (19, 0.30389354)]
Speech 43 - Topic Distribution: [(11, 0.9994303)]
Speech 44 - Topic Distribution: [(1, 0.32041743), (3, 0.01547567), (8, 0.056188628), (9, 0.019899642), (13, 0.038324654), (18, 0.027143678), (19, 0.5152245)]
Speech 45 - Topic Distribution: [(1, 0.79870987), (17, 0.19863696)]
Speech 46 - Topic Distribution: [(2, 0.97067654), (16, 0.017889509)]
Speech 47 - Topic Distribution: [(3, 0.88729227), (19, 0.112197466)]
Speech 48 - Topic Distribution: [(0, 0.40570116), (2, 0.45325002), (9, 0.085247636), (11, 0.019411938), (12, 0.024868263)]
Speech 49 - Topic Distribution: [(2, 0.64973825), (9, 0.11570961), (11, 0.07214543), (16, 0.14670782), (17, 0.0152960075)]
Speech 50 - Topic Distribution: [(4, 0.31961945), (5, 0.10026936), (12, 0.14386651), (16, 0.31997234), (19, 0.115879826)]
Speech 51 - Topic Distribution: [(1, 0.98993754)]
Speech 52 - Topic Distribution: [(6, 0.1032318), (9, 0.035405677), (11, 0.39439857), (12, 0.3707825), (13, 0.09418126)]
Speech 53 - Topic Distribution: [(1, 0.095432475), (6, 0.03850579), (8, 0.025602542), (11, 0.036801495), (12, 0.19389142), (13, 0.15984678), (15, 0.41133606), (16, 0.018027285), (18, 0.017980136)]
Speech 54 - Topic Distribution: [(3, 0.05750668), (8, 0.902971), (11, 0.01082267), (19, 0.028410258)]
Speech 55 - Topic Distribution: [(2, 0.021081554), (8, 0.45683676), (9, 0.33052507), (13, 0.062432814), (17, 0.088049866), (18, 0.032194912)]
Speech 56 - Topic Distribution: [(1, 0.92286605), (17, 0.07247182)]
Speech 57 - Topic Distribution: [(2, 0.99941444)]
Speech 58 - Topic Distribution: [(2, 0.21067904), (6, 0.06909705), (12, 0.13804619), (15, 0.5740644)]
Speech 59 - Topic Distribution: [(1, 0.08554409), (3, 0.26077443), (8, 0.04636651), (9, 0.018159026), (15, 0.041674253), (17, 0.04371354), (19, 0.503555)]
Speech 60 - Topic Distribution: [(0, 0.040937256), (6, 0.024279796), (9, 0.51821434), (11, 0.13571018), (12, 0.01154695), (13, 0.13369192), (15, 0.13252148)]
Speech 61 - Topic Distribution: [(1, 0.83639294), (17, 0.15513663)]
Speech 62 - Topic Distribution: [(2, 0.5378555), (16, 0.46165597)]
Speech 63 - Topic Distribution: [(3, 0.03705068), (8, 0.8365306), (9, 0.070087865), (16, 0.015998425), (17, 0.037496902)]
Speech 64 - Topic Distribution: [(1, 0.30689976), (16, 0.6839077)]
Speech 65 - Topic Distribution: [(1, 0.013841609), (19, 0.9842169)]
Speech 66 - Topic Distribution: [(2, 0.020539047), (3, 0.023858314), (9, 0.55321395), (11, 0.049922332), (13, 0.24724694), (17, 0.104827106)]
Speech 67 - Topic Distribution: [(2, 0.99957)]
Speech 68 - Topic Distribution: [(1, 0.07210944), (3, 0.04787194), (8, 0.6152635), (15, 0.12994458), (19, 0.13457671)]
Speech 69 - Topic Distribution: [(3, 0.0672648), (8, 0.35719654), (9, 0.08001644), (13, 0.056397777), (17, 0.43502018)]
Speech 70 - Topic Distribution: [(4, 0.4451261), (8, 0.031663354), (9, 0.29428136), (13, 0.059129454), (16, 0.14682224), (17, 0.014850151)]
Speech 71 - Topic Distribution: [(3, 0.025556792), (8, 0.96812516)]
Speech 72 - Topic Distribution: [(1, 0.5908103), (3, 0.010991849), (8, 0.21326932), (15, 0.15908647), (19, 0.017378028)]
Speech 73 - Topic Distribution: [(2, 0.30435097), (3, 0.020761132), (9, 0.18753383), (13, 0.28080302), (16, 0.013254616), (17, 0.18654309)]
Speech 74 - Topic Distribution: [(1, 0.8237611), (8, 0.057569623), (15, 0.118446626)]
Speech 75 - Topic Distribution: [(0, 0.18838318), (2, 0.013526804), (4, 0.067678235), (5, 0.07263078), (12, 0.19858965), (13, 0.084414884), (16, 0.34152472), (19, 0.015868735)]
Speech 76 - Topic Distribution: [(1, 0.72299147), (3, 0.02731094), (6, 0.017290242), (8, 0.057236213), (15, 0.17471299)]
Speech 77 - Topic Distribution: [(3, 0.05041762), (9, 0.7672729), (13, 0.13323407), (17, 0.024063015), (19, 0.01490622)]
Speech 78 - Topic Distribution: [(1, 0.85320735), (16, 0.080378115), (17, 0.06582069)]
Speech 79 - Topic Distribution: [(6, 0.076529995), (12, 0.46433464), (16, 0.14372627), (17, 0.01413566), (19, 0.2992125)]
Speech 80 - Topic Distribution: [(3, 0.82830644), (19, 0.17144933)]
Speech 81 - Topic Distribution: [(3, 0.020998916), (19, 0.9783748)]
Speech 82 - Topic Distribution: [(11, 0.995273)]
Speech 83 - Topic Distribution: [(3, 0.7070817), (8, 0.13557744), (15, 0.054261867), (19, 0.10270986)]
Speech 84 - Topic Distribution: [(3, 0.10550307), (8, 0.8633716), (11, 0.015495725), (19, 0.015280779)]
Speech 85 - Topic Distribution: [(16, 0.9995724)]
Speech 86 - Topic Distribution: [(6, 0.9278643), (19, 0.07052113)]
Speech 87 - Topic Distribution: [(16, 0.99951416)]
Speech 88 - Topic Distribution: [(1, 0.7509958), (15, 0.20379223), (19, 0.04492802)]
Speech 89 - Topic Distribution: [(1, 0.5579095), (9, 0.019767739), (16, 0.2820072), (17, 0.13528095)]
Speech 90 - Topic Distribution: [(2, 0.015328338), (3, 0.033837605), (8, 0.023123669), (9, 0.20259866), (11, 0.15042165), (13, 0.10394213), (16, 0.021837454), (17, 0.448612)]
Speech 91 - Topic Distribution: [(16, 0.99884063)]
Speech 92 - Topic Distribution: [(2, 0.21520269), (3, 0.01117771), (5, 0.011411136), (8, 0.12098947), (9, 0.03023382), (13, 0.1453042), (15, 0.26533687), (16, 0.047028407), (17, 0.09083434), (19, 0.062307823)]
Speech 93 - Topic Distribution: [(3, 0.8319638), (19, 0.16779214)]
Speech 94 - Topic Distribution: [(1, 0.63311744), (8, 0.041281313), (15, 0.31969804)]
Speech 95 - Topic Distribution: [(2, 0.96106684), (9, 0.03848838)]
Speech 96 - Topic Distribution: [(0, 0.15404584), (5, 0.032282036), (12, 0.079726554), (16, 0.733509)]
Speech 97 - Topic Distribution: [(8, 0.07340891), (13, 0.044595003), (15, 0.06553568), (16, 0.2554444), (17, 0.5608028)]
Speech 98 - Topic Distribution: [(3, 0.3941057), (9, 0.32753775), (12, 0.08440286), (13, 0.012372779), (15, 0.10174567), (17, 0.077342)]
Speech 99 - Topic Distribution: [(1, 0.56246936), (16, 0.12339112), (17, 0.3136667)]
Speech 100 - Topic Distribution: [(1, 0.09254293), (3, 0.4180008), (8, 0.29107657), (19, 0.19812793)]
Speech 101 - Topic Distribution: [(8, 0.02455058), (9, 0.032791827), (13, 0.06291873), (17, 0.8637778)]
Speech 102 - Topic Distribution: [(19, 0.9997039)]
Speech 103 - Topic Distribution: [(1, 0.23377113), (3, 0.049208898), (8, 0.20576146), (15, 0.31727895), (19, 0.19368275)]
Speech 104 - Topic Distribution: [(3, 0.73700726), (13, 0.24256249), (15, 0.01067455)]
Speech 105 - Topic Distribution: [(8, 0.07547491), (9, 0.060396764), (11, 0.015742261), (13, 0.22277343), (17, 0.6251183)]
Speech 106 - Topic Distribution: [(0, 0.047238506), (2, 0.040350847), (9, 0.12214757), (13, 0.18511601), (16, 0.5672562), (18, 0.03663835)]
Speech 107 - Topic Distribution: [(1, 0.18055844), (2, 0.036729965), (8, 0.1111007), (15, 0.09539642), (18, 0.57573277)]
Speech 108 - Topic Distribution: [(1, 0.022970855), (13, 0.24093743), (16, 0.036100373), (17, 0.699691)]
Speech 109 - Topic Distribution: [(0, 0.10735248), (15, 0.89212596)]
Speech 110 - Topic Distribution: [(1, 0.56181246), (8, 0.3801483), (15, 0.057748336)]
Speech 111 - Topic Distribution: [(2, 0.05501916), (4, 0.14982764), (13, 0.14529712), (16, 0.08109643), (17, 0.56805843)]
Speech 112 - Topic Distribution: [(13, 0.9366677), (15, 0.062257312)]
Speech 113 - Topic Distribution: [(16, 0.99946684)]
Speech 114 - Topic Distribution: [(3, 0.02772318), (4, 0.026981952), (5, 0.5723983), (11, 0.018470487), (12, 0.15054813), (17, 0.073236324), (19, 0.13019617)]
Speech 115 - Topic Distribution: [(1, 0.034037217), (8, 0.041920967), (9, 0.021352397), (15, 0.17224266), (17, 0.730012)]
Speech 116 - Topic Distribution: [(2, 0.99951005)]
Speech 117 - Topic Distribution: [(0, 0.066149235), (1, 0.081127815), (6, 0.042276353), (8, 0.22761814), (15, 0.048483286), (18, 0.5259099)]
Speech 118 - Topic Distribution: [(1, 0.32872677), (2, 0.032919705), (8, 0.070271455), (16, 0.11314279), (17, 0.38791913), (18, 0.06661715)]
Speech 119 - Topic Distribution: [(8, 0.07197567), (13, 0.34477827), (17, 0.566566)]
Speech 120 - Topic Distribution: [(1, 0.18755867), (12, 0.23319104), (16, 0.075298265), (17, 0.16193792), (19, 0.341527)]
Speech 121 - Topic Distribution: [(2, 0.18096232), (4, 0.484328), (9, 0.059324905), (13, 0.046907447), (16, 0.22492427)]
Speech 122 - Topic Distribution: [(6, 0.23697026), (9, 0.056012083), (12, 0.047991943), (15, 0.36554405), (17, 0.018903894), (18, 0.26337656)]
Speech 123 - Topic Distribution: [(0, 0.06571745), (1, 0.07429153), (8, 0.28789574), (9, 0.04100372), (13, 0.015614504), (18, 0.5013607)]
Speech 124 - Topic Distribution: [(1, 0.067130186), (8, 0.026191702), (13, 0.22104761), (16, 0.13946472), (17, 0.5458215)]
Speech 125 - Topic Distribution: [(2, 0.05232236), (8, 0.040708035), (9, 0.02859843), (13, 0.043276183), (15, 0.7937695), (17, 0.041057568)]
Speech 126 - Topic Distribution: [(16, 0.9995669)]
Speech 127 - Topic Distribution: [(8, 0.3117092), (13, 0.5859026), (15, 0.021025458), (17, 0.046918456), (18, 0.034122176)]
Speech 128 - Topic Distribution: [(2, 0.45063448), (3, 0.31677294), (9, 0.232099)]
Speech 129 - Topic Distribution: [(1, 0.2613152), (13, 0.017359696), (16, 0.014765821), (17, 0.7043399)]
Speech 130 - Topic Distribution: [(4, 0.5517939), (6, 0.23815599), (16, 0.14421083), (19, 0.064301856)]
Speech 131 - Topic Distribution: [(1, 0.053301908), (3, 0.72553027), (16, 0.1768723), (17, 0.037049737)]
Speech 132 - Topic Distribution: [(2, 0.2763627), (7, 0.48796114), (9, 0.108484134), (13, 0.12678155)]
Speech 133 - Topic Distribution: [(1, 0.5846391), (8, 0.119256444), (16, 0.053293664), (17, 0.23989068)]
Speech 134 - Topic Distribution: [(1, 0.56562096), (8, 0.024699753), (15, 0.40268064)]
Speech 135 - Topic Distribution: [(2, 0.45574233), (3, 0.23587783), (9, 0.28193521), (16, 0.02604102)]
Speech 136 - Topic Distribution: [(4, 0.011609474), (16, 0.9879329)]
Speech 137 - Topic Distribution: [(0, 0.12871048), (1, 0.19070211), (8, 0.25131813), (15, 0.4266464)]
Speech 138 - Topic Distribution: [(0, 0.119204774), (1, 0.14518216), (6, 0.02655523), (8, 0.046146356), (15, 0.6627)]
Speech 139 - Topic Distribution: [(1, 0.015622022), (2, 0.03504964), (3, 0.68625844), (13, 0.08202093), (16, 0.051869918), (17, 0.12112173)]
Speech 140 - Topic Distribution: [(11, 0.04411344), (12, 0.93011826), (18, 0.024124745)]
Speech 141 - Topic Distribution: [(6, 0.089796156), (12, 0.40741897), (16, 0.2647812), (19, 0.23518303)]
Speech 142 - Topic Distribution: [(2, 0.28620344), (3, 0.028531704), (9, 0.2708768), (13, 0.068748616), (16, 0.286665), (17, 0.058610503)]
Speech 143 - Topic Distribution: [(9, 0.11225359), (13, 0.17629892), (17, 0.7010412)]
Speech 144 - Topic Distribution: [(2, 0.13286161), (9, 0.22016947), (13, 0.44797567), (16, 0.060303297), (17, 0.13222162)]
Speech 145 - Topic Distribution: [(2, 0.022027321), (4, 0.66267407), (9, 0.057041083), (13, 0.027416317), (16, 0.22810861)]
Speech 146 - Topic Distribution: [(1, 0.021326229), (4, 0.09225819), (12, 0.1449944), (16, 0.73845774)]
Speech 147 - Topic Distribution: [(4, 0.34737208), (12, 0.17174166), (16, 0.48041442)]
Speech 148 - Topic Distribution: [(9, 0.02930927), (13, 0.9387765), (17, 0.031546995)]
Speech 149 - Topic Distribution: [(2, 0.99002033)]
Speech 150 - Topic Distribution: [(3, 0.011457015), (8, 0.7556703), (9, 0.106272876), (15, 0.080521606), (16, 0.03398684)]
Speech 151 - Topic Distribution: [(1, 0.24213675), (17, 0.7545963)]
Speech 152 - Topic Distribution: [(1, 0.12453836), (8, 0.15662993), (9, 0.021734148), (15, 0.33545938), (17, 0.3176371), (18, 0.039373394)]
Speech 153 - Topic Distribution: [(2, 0.38644797), (3, 0.1354882), (9, 0.041924145), (13, 0.045898523), (16, 0.37769538), (17, 0.012178354)]
Speech 154 - Topic Distribution: [(9, 0.0194894), (13, 0.9790077)]
Speech 155 - Topic Distribution: [(1, 0.15737613), (3, 0.18600024), (8, 0.025549265), (13, 0.021234475), (16, 0.09884771), (17, 0.49485794)]
Speech 156 - Topic Distribution: [(1, 0.5012485), (6, 0.06058314), (12, 0.020289592), (17, 0.04793822), (19, 0.36956945)]
Speech 157 - Topic Distribution: [(2, 0.37691504), (3, 0.20107754), (13, 0.059498496), (16, 0.25441572), (17, 0.100381345)]
Speech 158 - Topic Distribution: [(1, 0.6718753), (4, 0.0128867645), (8, 0.03955739), (9, 0.020300863), (15, 0.2066634), (19, 0.04837073)]
Speech 159 - Topic Distribution: [(11, 0.022155995), (16, 0.93365854), (19, 0.043708377)]
Speech 160 - Topic Distribution: [(6, 0.19021945), (12, 0.8077782)]
Speech 161 - Topic Distribution: [(2, 0.2668011), (4, 0.31329858), (9, 0.024671918), (11, 0.035945453), (17, 0.09107737), (19, 0.26031482)]
Speech 162 - Topic Distribution: [(1, 0.1788287), (3, 0.22494502), (8, 0.12028681), (15, 0.11387722), (17, 0.13833308), (19, 0.2233945)]
Speech 163 - Topic Distribution: [(1, 0.046386894), (3, 0.18489712), (13, 0.2569707), (16, 0.04811011), (17, 0.46236846)]
Speech 164 - Topic Distribution: [(9, 0.5464018), (13, 0.383679), (16, 0.0695548)]
Speech 165 - Topic Distribution: [(0, 0.011883163), (2, 0.01512576), (5, 0.02079307), (11, 0.09527406), (12, 0.13293307), (16, 0.7236205)]
Speech 166 - Topic Distribution: [(3, 0.17262113), (11, 0.17340192), (13, 0.14371891), (16, 0.014235781), (17, 0.49364904)]
Speech 167 - Topic Distribution: [(1, 0.017660508), (2, 0.011543698), (8, 0.021740569), (9, 0.8224193), (13, 0.0908498), (16, 0.016549304), (17, 0.015293393)]
Speech 168 - Topic Distribution: [(14, 0.99945045)]
Speech 169 - Topic Distribution: [(6, 0.06452677), (12, 0.23561248), (16, 0.060908377), (19, 0.6367849)]
Speech 170 - Topic Distribution: [(1, 0.015374351), (3, 0.15239532), (8, 0.040265474), (9, 0.33756647), (13, 0.073352374), (16, 0.044888984), (17, 0.33551505)]
Speech 171 - Topic Distribution: [(9, 0.07189027), (13, 0.50163394), (17, 0.42602265)]
Speech 172 - Topic Distribution: [(6, 0.048186332), (9, 0.05449065), (13, 0.16811515), (17, 0.7262727)]
Speech 173 - Topic Distribution: [(3, 0.015891124), (9, 0.113983475), (13, 0.3811008), (17, 0.48856616)]
Speech 174 - Topic Distribution: [(2, 0.34826902), (3, 0.040952027), (9, 0.43158698), (13, 0.12339368), (17, 0.054657135)]
Speech 175 - Topic Distribution: [(3, 0.43911886), (9, 0.19667315), (13, 0.060248543), (16, 0.2903232), (17, 0.013210804)]
Speech 176 - Topic Distribution: [(9, 0.11649683), (17, 0.88136494)]
Speech 177 - Topic Distribution: [(3, 0.20388012), (8, 0.08691356), (9, 0.20899111), (11, 0.023601852), (13, 0.094360165), (17, 0.38022485)]
Speech 178 - Topic Distribution: [(3, 0.19480383), (7, 0.12580836), (9, 0.02597249), (12, 0.08207147), (13, 0.39665398), (15, 0.104954354), (17, 0.06908394)]
Speech 179 - Topic Distribution: [(8, 0.85392815), (16, 0.07951953), (17, 0.06359027)]
Speech 180 - Topic Distribution: [(1, 0.061630417), (8, 0.030647768), (9, 0.049489345), (13, 0.4843436), (17, 0.3735673)]
Speech 181 - Topic Distribution: [(0, 0.027868798), (4, 0.119672745), (5, 0.031730566), (12, 0.33635467), (16, 0.48399976)]
Speech 182 - Topic Distribution: [(4, 0.13103113), (8, 0.026939696), (16, 0.59542143), (17, 0.2383615)]
Speech 183 - Topic Distribution: [(5, 0.02126374), (13, 0.704822), (16, 0.14304115), (17, 0.12932746)]
Speech 184 - Topic Distribution: [(8, 0.14756747), (9, 0.043253835), (13, 0.5495592), (17, 0.23005682), (18, 0.026695957)]
Speech 185 - Topic Distribution: [(4, 0.3295321), (16, 0.4378628), (17, 0.23225231)]
Speech 186 - Topic Distribution: [(4, 0.5069363), (16, 0.31076837), (17, 0.16184242)]
Speech 187 - Topic Distribution: [(8, 0.09287993), (11, 0.012033394), (13, 0.5022906), (16, 0.02734434), (17, 0.19583483), (18, 0.16930497)]
Speech 188 - Topic Distribution: [(0, 0.17517556), (9, 0.021834327), (12, 0.5201685), (16, 0.27484858)]
Speech 189 - Topic Distribution: [(2, 0.2986025), (6, 0.2079319), (10, 0.0114532495), (12, 0.25498092), (19, 0.22552034)]
Speech 190 - Topic Distribution: [(3, 0.07562645), (9, 0.80603087), (11, 0.010888593), (13, 0.104797594)]
Speech 191 - Topic Distribution: [(5, 0.19019629), (9, 0.3043448), (13, 0.2763024), (16, 0.030339917), (17, 0.1915875)]
Speech 192 - Topic Distribution: [(1, 0.06720364), (5, 0.02583864), (13, 0.7389171), (16, 0.093290254), (17, 0.074505575)]

In [30]:
import pandas as pd

# Define the indices of the topics you are interested in
topics_of_interest = [0, 1, 4]  # Adjust based on your topics of interest

# Create an empty DataFrame to store relevant speeches
relevant_speeches_df = pd.DataFrame(columns=speeches_df.columns)

# Iterate through each speech and filter based on topics of interest
for idx, speech in speeches_df.iterrows():
    topic_distribution = get_topic_distribution(speech['text'])
    # Check if any of the topics of interest have significant probability in the topic distribution
    relevant_topics = [topic for topic, prob in topic_distribution if topic in topics_of_interest and prob > 0.2]
    if relevant_topics:
        relevant_speeches_df = relevant_speeches_df.append(speech, ignore_index=True)

# Print or do something else with the relevant speeches DataFrame
print(relevant_speeches_df)

AttributeError: 'DataFrame' object has no attribute 'append'

In [29]:
speeches_df.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Link URL,Author,date,Title,text,sentiment vader,vader_sentiment,positive_score,negative_score,uncertainty_score,Polarity_Score,processed_text
0,0,0,1053,https://www.federalreserve.gov/newsevents/spee...,Governor Susan Schmidt Bies,2006-01-18,Productivity and Economic Outlook,appreciate opportunity speak today productivit...,positive,0.225877,60402393,118486857,81571443,0.200000,"[appreciate, opportunity, speak, today, produc..."
1,1,1,1052,https://www.federalreserve.gov/newsevents/spee...,Governor Susan Schmidt Bies,2006-02-02,The Continuous Challenges of Risk Management,thank invitation speak today remark focus cont...,positive,0.196206,60402393,118486857,81571443,-0.157895,"[thank, invitation, speak, today, remark, focu..."
2,2,2,1051,https://www.federalreserve.gov/newsevents/spee...,Chairman Ben S. Bernanke,2006-02-06,Remarks at ceremonial swearing-in by President...,good morning would like begin thanking preside...,positive,0.742904,60402393,118486857,81571443,0.793103,"[good, morning, would, like, begin, thanking, ..."
3,3,3,1050,https://www.federalreserve.gov/newsevents/spee...,"Vice Chairman Roger W. Ferguson, Jr.",2006-02-23,"Globalization, Insurers, and Regulators: Share...",honored deliver keynote address important inte...,positive,0.423985,60402393,118486857,81571443,0.156463,"[honored, deliver, keynote, address, important..."
4,4,4,1048,https://www.federalreserve.gov/newsevents/spee...,"Vice Chairman Roger W. Ferguson, Jr.",2006-02-24,The Importance of Education,pleased opportunity part applied physic labora...,positive,0.414621,60402393,118486857,81571443,0.301205,"[pleased, opportunity, part, applied, physic, ..."

In [34]:
#don't need 2, 5, 9, 11, 15, 16, 18
import pandas as pd

# Define the indices of the topics you are interested in
topics_of_interest = [0, 1, 3, 4, 6, 7, 8, 10, 12, 13, 14, 17, 19]  # Adjust based on your topics of interest

# Create an empty list to store relevant speeches
relevant_speeches = []

# Iterate through each speech and filter based on topics of interest
for idx, speech in speeches_df.iterrows():
    topic_distribution = get_topic_distribution(speech['text'])
    # Check if any of the topics of interest have significant probability in the topic distribution
    relevant_topics = [topic for topic, prob in topic_distribution if topic in topics_of_interest and prob > 0.2]
    if relevant_topics:
        relevant_speeches.append(speech)

# Convert the list of relevant speeches into a DataFrame
relevant_speeches_df = pd.DataFrame(relevant_speeches)

# Print or do something else with the relevant speeches DataFrame
print(relevant_speeches_df)

     Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  \
0               0             0        1053
2               2             2        1051
3               3             3        1050
4               4             4        1048
5               5             5        1047
..            ...           ...         ...
890           890           890          18
891           891           891          14
893           893           893          11
896           896           896           7
900           900           900           0

                                              Link URL  \
0    https://www.federalreserve.gov/newsevents/spee...
2    https://www.federalreserve.gov/newsevents/spee...
3    https://www.federalreserve.gov/newsevents/spee...
4    https://www.federalreserve.gov/newsevents/spee...
5    https://www.federalreserve.gov/newsevents/spee...
..                                                 ...
890  https://www.federalreserve.gov/newsevents/spee...
891  https://www.federalreserve.gov/newsevents/spee...
893  https://www.federalreserve.gov/newsevents/spee...
896  https://www.federalreserve.gov/newsevents/spee...
900  https://www.federalreserve.gov/newsevents/spee...

                                   Author       date  \
0             Governor Susan Schmidt Bies 2006-01-18
2                Chairman Ben S. Bernanke 2006-02-06
3    Vice Chairman Roger W. Ferguson, Jr. 2006-02-23
4    Vice Chairman Roger W. Ferguson, Jr. 2006-02-24
5    Vice Chairman Roger W. Ferguson, Jr. 2006-03-03
..                                    ...        ...
890        Governor Christopher J. Waller 2023-11-07
891        Vice Chair Philip N. Jefferson 2023-11-08
893                 Governor Lisa D. Cook 2023-11-13
896        Governor Christopher J. Waller 2023-11-28
900        Governor Christopher J. Waller 2024-01-16

                                                 Title  \
0                    Productivity and Economic Outlook
2    Remarks at ceremonial swearing-in by President...
3    Globalization, Insurers, and Regulators: Share...
4                          The Importance of Education
5               Economic Outlook for the United States
..                                                 ...
890      Using Economic Data to Understand the Economy
891  Research and Statistics Centennial Anniversary...
893                                  Welcoming Remarks
896                     Something Appears to Be Giving
900        Almost as Good as It Gets…But Will It Last?

                                                  text sentiment vader  \
0    appreciate opportunity speak today productivit...        positive
2    good morning would like begin thanking preside...        positive
3    honored deliver keynote address important inte...        positive
4    pleased opportunity part applied physic labora...        positive
5    appreciate opportunity speak today macroeconom...        positive
..                                                 ...             ...
890  thank katrina inviting hope know federal reser...        positive
891  thank stacey thank organizer thoughtprovoking ...        positive
893  good morning welcome annual conference nontrad...        positive
896  last month gave speech entitled somethings got...        positive
900  thank david wessel thank brookings opportunity...        positive

     vader_sentiment  positive_score  negative_score  uncertainty_score  \
0           0.225877        60402393       118486857           81571443
2           0.742904        60402393       118486857           81571443
3           0.423985        60402393       118486857           81571443
4           0.414621        60402393       118486857           81571443
5           0.333437        60402393       118486857           81571443
..               ...             ...             ...                ...
890         0.085969        60402393       118486857           81571443
891         0.153182        60402393       118486857           81571443
893         0.380813        60402393       118486857           81571443
896         0.270940        60402393       118486857           81571443
900         0.083225        60402393       118486857           81571443

     Polarity_Score                                     processed_text
0          0.200000  [appreciate, opportunity, speak, today, produc...
2          0.793103  [good, morning, would, like, begin, thanking, ...
3          0.156463  [honored, deliver, keynote, address, important...
4          0.301205  [pleased, opportunity, part, applied, physic, ...
5         -0.278481  [appreciate, opportunity, speak, today, macroe...
..              ...                                                ...
890        0.000000  [thank, katrina, inviting, hope, know, federal...
891       -0.214286  [thank, stacey, thank, organizer, provoking, t...
893        0.446809  [good, morning, welcome, annual, conference, n...
896       -0.220779  [last, month, gave, speech, entitled, somethin...
900       -0.321739  [thank, david, wessel, thank, brookings, oppor...

[636 rows x 15 columns]

In [32]:
speeches_df.tail()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Link URL,Author,date,Title,text,sentiment vader,vader_sentiment,positive_score,negative_score,uncertainty_score,Polarity_Score,processed_text
896,896,896,7,https://www.federalreserve.gov/newsevents/spee...,Governor Christopher J. Waller,2023-11-28,Something Appears to Be Giving,last month gave speech entitled somethings got...,positive,0.270940,60402393,118486857,81571443,-0.220779,"[last, month, gave, speech, entitled, somethin..."
897,897,897,4,https://www.federalreserve.gov/newsevents/spee...,Vice Chair for Supervision Michael S. Barr,2023-12-01,The Importance of Effective Liquidity Risk Man...,thank opportunity speak im delighted celebrate...,positive,0.079550,60402393,118486857,81571443,-0.526786,"[thank, opportunity, speak, im, delighted, cel..."
898,898,898,2,https://www.federalreserve.gov/newsevents/spee...,Governor Michelle W. Bowman,2023-12-05,Building a More Inclusive Financial System thr...,would like thank aspen institute inviting join...,positive,0.385244,60402393,118486857,81571443,0.482759,"[would, like, thank, aspen, institute, invitin..."
899,899,899,1,https://www.federalreserve.gov/newsevents/spee...,Governor Michelle W. Bowman,2024-01-08,New Year’s Resolutions for Bank Regulatory Pol...,pleasure join afternoon south carolina communi...,positive,0.264607,60402393,118486857,81571443,-0.313953,"[pleasure, join, afternoon, south, carolina, c..."
900,900,900,0,https://www.federalreserve.gov/newsevents/spee...,Governor Christopher J. Waller,2024-01-16,Almost as Good as It Gets…But Will It Last?,thank david wessel thank brookings opportunity...,positive,0.083225,60402393,118486857,81571443,-0.321739,"[thank, david, wessel, thank, brookings, oppor..."

In [33]:
relevant_speeches_df.tail()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Link URL,Author,date,Title,text,sentiment vader,vader_sentiment,positive_score,negative_score,uncertainty_score,Polarity_Score,processed_text
874,874,874,41,https://www.federalreserve.gov/newsevents/spee...,Governor Michelle W. Bowman,2023-09-26,Welcoming Remarks,welcome thank joining u federal reserve commun...,positive,0.115287,60402393,118486857,81571443,0.069767,"[welcome, thank, joining, federal, reserve, co..."
881,881,881,31,https://www.federalreserve.gov/newsevents/spee...,Governor Christopher J. Waller,2023-10-10,Monetary Policy Analysis and the Development o...,pleasure honor legacy bennett mccallum discuss...,positive,0.220939,60402393,118486857,81571443,0.044248,"[pleasure, honor, legacy, bennett, mccallum, d..."
884,884,884,28,https://www.federalreserve.gov/newsevents/spee...,Governor Christopher J. Waller,2023-10-18,Something’s Got to Give,thank professor scobie thank european economic...,positive,0.352477,60402393,118486857,81571443,-0.149425,"[thank, professor, scobie, thank, european, ec..."
896,896,896,7,https://www.federalreserve.gov/newsevents/spee...,Governor Christopher J. Waller,2023-11-28,Something Appears to Be Giving,last month gave speech entitled somethings got...,positive,0.270940,60402393,118486857,81571443,-0.220779,"[last, month, gave, speech, entitled, somethin..."
900,900,900,0,https://www.federalreserve.gov/newsevents/spee...,Governor Christopher J. Waller,2024-01-16,Almost as Good as It Gets…But Will It Last?,thank david wessel thank brookings opportunity...,positive,0.083225,60402393,118486857,81571443,-0.321739,"[thank, david, wessel, thank, brookings, oppor..."

In [36]:
relevant_speeches_df.to_excel('FEDdatasentimentfinal44.xlsx', index=False)

In [2]:
import gensim
from gensim import corpora
from gensim.models import LdaModel
from gensim.models.ldamulticore import LdaMulticore
from gensim.utils import simple_preprocess
from nltk.corpus import stopwords
import pandas as pd

In [5]:
import pandas as pd
from gensim.utils import simple_preprocess
from nltk.corpus import stopwords

# Example function for text preprocessing
def preprocess_text(text):
    stop_words = set(stopwords.words('english'))
    
    # Convert non-string values to string
    if not isinstance(text, str):
        text = str(text)
        
    tokens = simple_preprocess(text)
    tokens = [token for token in tokens if token not in stop_words]
    return tokens

# Load central bank speeches data
# Replace 'your_speeches.csv' with the path to your CSV file containing speeches
speeches_df = pd.read_excel('ECBdatasentiment224.xlsx')

# Preprocess speeches
speeches_df['processed_text'] = speeches_df['text'].apply(preprocess_text)

# Create dictionary and corpus
dictionary = corpora.Dictionary(speeches_df['processed_text'])
corpus = [dictionary.doc2bow(text) for text in speeches_df['processed_text']]

# Train LDA model
lda_model = LdaMulticore(corpus=corpus,
                          id2word=dictionary,
                          num_topics=10, # Adjust based on your expectation of the number of topics
                          workers=4,
                          passes=10)

# Function to get topic distribution for a speech
def get_topic_distribution(text):
    bow = dictionary.doc2bow(preprocess_text(text))
    topic_distribution = lda_model.get_document_topics(bow)
    return topic_distribution

In [3]:
for idx, speech in speeches_df.iterrows():
    topic_distribution = get_topic_distribution(speech['text'])
    print(f"Speech {idx} - Topic Distribution: {topic_distribution}")

Speech 0 - Topic Distribution: [(0, 0.096061796), (3, 0.90342)]
Speech 1 - Topic Distribution: [(1, 0.17246792), (15, 0.8163452)]
Speech 2 - Topic Distribution: [(0, 0.12883228), (1, 0.17031251), (2, 0.012405928), (3, 0.4210172), (7, 0.074726395), (12, 0.18291551)]
Speech 3 - Topic Distribution: [(1, 0.35859624), (2, 0.5473718), (12, 0.09304058)]
Speech 4 - Topic Distribution: [(1, 0.6171017), (3, 0.09790273), (7, 0.16210887), (12, 0.12085614)]
Speech 5 - Topic Distribution: [(1, 0.029553413), (2, 0.3672291), (9, 0.5892772), (12, 0.012769013)]
Speech 6 - Topic Distribution: [(1, 0.10283034), (2, 0.016563376), (3, 0.033634238), (6, 0.2851981), (15, 0.5274335), (16, 0.029394027)]
Speech 7 - Topic Distribution: [(0, 0.13107143), (1, 0.02321957), (2, 0.12432649), (3, 0.35801253), (6, 0.095100075), (7, 0.22072478), (12, 0.046561845)]
Speech 8 - Topic Distribution: [(1, 0.49323723), (3, 0.3720982), (6, 0.13400923)]
Speech 9 - Topic Distribution: [(2, 0.52395874), (6, 0.10336803), (12, 0.37183744)]
Speech 10 - Topic Distribution: [(6, 0.11206156), (7, 0.37621385), (12, 0.5004503)]
Speech 11 - Topic Distribution: [(2, 0.23999894), (9, 0.6872972), (12, 0.07230655)]
Speech 12 - Topic Distribution: [(2, 0.83774847), (12, 0.16039467)]
Speech 13 - Topic Distribution: [(1, 0.21265991), (2, 0.047655016), (8, 0.38214976), (15, 0.27427745), (17, 0.08147151)]
Speech 14 - Topic Distribution: [(2, 0.095042005), (3, 0.055565525), (6, 0.26867002), (7, 0.5451412), (12, 0.03454399)]
Speech 15 - Topic Distribution: [(2, 0.71012634), (6, 0.21870443), (12, 0.04159113), (19, 0.023584742)]
Speech 16 - Topic Distribution: [(2, 0.64706576), (12, 0.34926423)]
Speech 17 - Topic Distribution: [(1, 0.043578673), (2, 0.26042306), (7, 0.6078454), (9, 0.049940832), (12, 0.036713183)]
Speech 18 - Topic Distribution: [(1, 0.62383085), (2, 0.08911175), (6, 0.19029655), (9, 0.0958168)]
Speech 19 - Topic Distribution: [(0, 0.09948972), (2, 0.28076756), (6, 0.012752484), (12, 0.60277575)]
Speech 20 - Topic Distribution: [(7, 0.23691142), (9, 0.5285164), (12, 0.21435489), (13, 0.020006284)]
Speech 21 - Topic Distribution: [(2, 0.51002187), (9, 0.031708404), (12, 0.45777526)]
Speech 22 - Topic Distribution: [(1, 0.8698073), (8, 0.065164484), (15, 0.018282037), (17, 0.024191424), (19, 0.013787818)]
Speech 23 - Topic Distribution: [(1, 0.74004525), (3, 0.07594034), (4, 0.1814848)]
Speech 24 - Topic Distribution: [(0, 0.09002875), (1, 0.19892015), (2, 0.08612108), (8, 0.36108294), (9, 0.0629927), (12, 0.1699673), (15, 0.024085755)]
Speech 25 - Topic Distribution: [(1, 0.39515653), (3, 0.3453819), (6, 0.032100197), (7, 0.14906314), (9, 0.07740165)]
Speech 26 - Topic Distribution: [(1, 0.392089), (2, 0.26231483), (7, 0.11429683), (9, 0.2308282)]
Speech 27 - Topic Distribution: [(1, 0.6874088), (3, 0.31143352)]
Speech 28 - Topic Distribution: [(0, 0.08467784), (1, 0.04039255), (13, 0.09947628), (16, 0.7750821)]
Speech 29 - Topic Distribution: [(2, 0.23734304), (9, 0.6171519), (12, 0.14517042)]
Speech 30 - Topic Distribution: [(1, 0.11828581), (2, 0.47346628), (7, 0.03302357), (9, 0.3672531)]
Speech 31 - Topic Distribution: [(2, 0.3269767), (9, 0.21625283), (12, 0.45641512)]
Speech 32 - Topic Distribution: [(1, 0.3543905), (2, 0.31438133), (8, 0.26360875), (19, 0.058638424)]
Speech 33 - Topic Distribution: [(2, 0.57076156), (9, 0.20286041), (12, 0.22586435)]
Speech 34 - Topic Distribution: [(2, 0.5524787), (9, 0.2043134), (12, 0.2425467)]
Speech 35 - Topic Distribution: [(13, 0.96984035), (16, 0.028516341)]
Speech 36 - Topic Distribution: [(1, 0.7224855), (3, 0.13734533), (13, 0.11261087), (19, 0.025908759)]
Speech 37 - Topic Distribution: [(0, 0.014341877), (3, 0.9239347), (6, 0.06102166)]
Speech 38 - Topic Distribution: [(1, 0.030016676), (7, 0.35327253), (9, 0.078961045), (11, 0.020100163), (15, 0.15637052), (19, 0.35562393)]
Speech 39 - Topic Distribution: [(2, 0.18155387), (9, 0.775912), (12, 0.04222671)]
Speech 40 - Topic Distribution: [(2, 0.7198182), (9, 0.017271854), (12, 0.2603902)]
Speech 41 - Topic Distribution: [(0, 0.07162662), (2, 0.015388943), (3, 0.8284772), (6, 0.08323544)]
Speech 42 - Topic Distribution: [(0, 0.19138898), (1, 0.1289798), (3, 0.021300847), (6, 0.6470023)]
Speech 43 - Topic Distribution: [(0, 0.15479787), (1, 0.054680966), (2, 0.6332279), (12, 0.15446)]
Speech 44 - Topic Distribution: [(2, 0.23869905), (6, 0.56036246), (12, 0.19987077)]
Speech 45 - Topic Distribution: [(2, 0.4492305), (9, 0.2259971), (12, 0.31483722)]
Speech 46 - Topic Distribution: [(0, 0.34201813), (2, 0.45639735), (3, 0.06996378), (6, 0.03990794), (12, 0.06213227), (13, 0.028725216)]
Speech 47 - Topic Distribution: [(1, 0.23562737), (2, 0.085571766), (9, 0.0141594475), (15, 0.5860325), (19, 0.077738196)]
Speech 48 - Topic Distribution: [(2, 0.010770018), (6, 0.98853636)]
Speech 49 - Topic Distribution: [(6, 0.05129877), (7, 0.5202729), (9, 0.029546231), (12, 0.3783726)]
Speech 50 - Topic Distribution: [(2, 0.17494345), (3, 0.042191025), (6, 0.6647077), (12, 0.108393475)]
Speech 51 - Topic Distribution: [(1, 0.10899083), (10, 0.0147886155), (15, 0.8753919)]
Speech 52 - Topic Distribution: [(1, 0.65686953), (2, 0.012743433), (3, 0.1876915), (6, 0.14200646)]
Speech 53 - Topic Distribution: [(0, 0.01296467), (1, 0.055070776), (16, 0.9314414)]
Speech 54 - Topic Distribution: [(1, 0.019174034), (2, 0.30440745), (8, 0.09355027), (9, 0.032675125), (15, 0.25535432), (17, 0.0948225), (19, 0.19665812)]
Speech 55 - Topic Distribution: [(1, 0.50550824), (3, 0.39808726), (7, 0.06611053), (12, 0.027974633)]
Speech 56 - Topic Distribution: [(2, 0.16668108), (6, 0.03719591), (9, 0.028225971), (12, 0.76765394)]
Speech 57 - Topic Distribution: [(1, 0.028531227), (2, 0.39941671), (15, 0.08870082), (16, 0.048334334), (19, 0.4238406)]
Speech 58 - Topic Distribution: [(2, 0.7381283), (3, 0.019400213), (6, 0.21149027), (12, 0.0108370595), (16, 0.013298581)]
Speech 59 - Topic Distribution: [(2, 0.50509036), (6, 0.21305485), (12, 0.28075826)]
Speech 60 - Topic Distribution: [(6, 0.09508585), (7, 0.5268789), (12, 0.3482581), (19, 0.01954539)]
Speech 61 - Topic Distribution: [(1, 0.16592135), (3, 0.83351684)]
Speech 62 - Topic Distribution: [(2, 0.45750725), (9, 0.16710696), (12, 0.310041), (19, 0.04934163)]
Speech 63 - Topic Distribution: [(2, 0.60261464), (9, 0.070679195), (12, 0.3258466)]
Speech 64 - Topic Distribution: [(1, 0.1536816), (2, 0.8202055), (6, 0.016068881)]
Speech 65 - Topic Distribution: [(2, 0.12454188), (8, 0.062569976), (17, 0.6837959), (19, 0.12683578)]
Speech 66 - Topic Distribution: [(3, 0.8331817), (13, 0.10679644), (16, 0.059330355)]
Speech 67 - Topic Distribution: [(2, 0.3455321), (9, 0.1999282), (12, 0.45425028)]
Speech 68 - Topic Distribution: [(0, 0.16714016), (1, 0.36254275), (2, 0.46537828)]
Speech 69 - Topic Distribution: [(1, 0.26338235), (2, 0.4100689), (15, 0.09097527), (16, 0.0101734195), (18, 0.123059474), (19, 0.10085236)]
Speech 70 - Topic Distribution: [(1, 0.06507805), (16, 0.93445027)]
Speech 71 - Topic Distribution: [(1, 0.51801497), (2, 0.017114172), (6, 0.041379526), (9, 0.08144832), (12, 0.33922166)]
Speech 72 - Topic Distribution: [(0, 0.09598112), (2, 0.10746885), (3, 0.25974354), (6, 0.43168664), (13, 0.10432378)]
Speech 73 - Topic Distribution: [(6, 0.010219209), (13, 0.9707793), (16, 0.018715028)]
Speech 74 - Topic Distribution: [(0, 0.18208507), (1, 0.7135282), (3, 0.10382289)]
Speech 75 - Topic Distribution: [(0, 0.013652808), (1, 0.124535464), (2, 0.70899737), (12, 0.138479)]
Speech 76 - Topic Distribution: [(2, 0.12307428), (8, 0.0605972), (9, 0.30327874), (12, 0.5044542)]
Speech 77 - Topic Distribution: [(1, 0.070254445), (2, 0.69790286), (7, 0.05109617), (8, 0.010509288), (12, 0.040240433), (15, 0.08910544), (16, 0.018179802), (18, 0.018861743)]
Speech 78 - Topic Distribution: [(1, 0.58176655), (2, 0.2568965), (9, 0.16112489)]
Speech 79 - Topic Distribution: [(1, 0.30102623), (2, 0.12647879), (3, 0.2994769), (10, 0.031569052), (12, 0.24074717)]
Speech 80 - Topic Distribution: [(2, 0.5965448), (6, 0.1582124), (12, 0.24448855)]
Speech 81 - Topic Distribution: [(2, 0.15391771), (9, 0.7080175), (12, 0.1377523)]
Speech 82 - Topic Distribution: [(1, 0.24857612), (2, 0.10977602), (8, 0.5898939), (9, 0.011221814), (15, 0.016391752)]
Speech 83 - Topic Distribution: [(1, 0.52902234), (3, 0.46910077)]
Speech 84 - Topic Distribution: [(1, 0.052362777), (13, 0.26549584), (16, 0.6810845)]
Speech 85 - Topic Distribution: [(1, 0.036241338), (2, 0.5104727), (9, 0.26394147), (12, 0.18202907)]
Speech 86 - Topic Distribution: [(1, 0.23625596), (2, 0.49191678), (6, 0.057268288), (12, 0.2137893)]
Speech 87 - Topic Distribution: [(2, 0.2925482), (6, 0.0238867), (9, 0.20735526), (12, 0.46098107), (19, 0.011706928)]
Speech 88 - Topic Distribution: [(1, 0.02152419), (2, 0.65268236), (6, 0.17752074), (12, 0.10571353), (16, 0.026316168)]
Speech 89 - Topic Distribution: [(2, 0.11560684), (9, 0.884008)]
Speech 90 - Topic Distribution: [(1, 0.3887598), (3, 0.603782)]
Speech 91 - Topic Distribution: [(0, 0.16585387), (1, 0.017582018), (2, 0.09877009), (7, 0.28775445), (8, 0.043304957), (12, 0.38595834)]
Speech 92 - Topic Distribution: [(13, 0.034795962), (16, 0.96466565)]
Speech 93 - Topic Distribution: [(1, 0.78345835), (2, 0.13369484), (3, 0.08166381)]
Speech 94 - Topic Distribution: [(1, 0.11461509), (2, 0.749084), (12, 0.13519111)]
Speech 95 - Topic Distribution: [(6, 0.060111407), (13, 0.2459468), (16, 0.6933931)]
Speech 96 - Topic Distribution: [(2, 0.57561296), (9, 0.32353666), (12, 0.097222894)]
Speech 97 - Topic Distribution: [(2, 0.55417806), (6, 0.06805095), (12, 0.37696946)]
Speech 98 - Topic Distribution: [(2, 0.10946737), (6, 0.09950049), (12, 0.79032797)]
Speech 99 - Topic Distribution: [(9, 0.9993064)]
Speech 100 - Topic Distribution: [(2, 0.15067771), (9, 0.17303875), (12, 0.6673933)]
Speech 101 - Topic Distribution: [(1, 0.07756736), (2, 0.08170358), (7, 0.089649014), (9, 0.7090956), (12, 0.016252188), (15, 0.025304707)]
Speech 102 - Topic Distribution: [(2, 0.5683343), (12, 0.43024668)]
Speech 103 - Topic Distribution: [(0, 0.039614473), (1, 0.29010543), (2, 0.35731107), (8, 0.11145109), (12, 0.06645962), (15, 0.1347548)]
Speech 104 - Topic Distribution: [(2, 0.69402087), (12, 0.30542755)]
Speech 105 - Topic Distribution: [(1, 0.06930412), (3, 0.9300384)]
Speech 106 - Topic Distribution: [(2, 0.99132013)]
Speech 107 - Topic Distribution: [(16, 0.9908977)]
Speech 108 - Topic Distribution: [(13, 0.6018343), (16, 0.3976812)]
Speech 109 - Topic Distribution: [(1, 0.02742725), (6, 0.023373077), (8, 0.09454168), (12, 0.48538452), (15, 0.35836837)]
Speech 110 - Topic Distribution: [(0, 0.09250262), (1, 0.03408898), (3, 0.86641467)]
Speech 111 - Topic Distribution: [(0, 0.42098776), (1, 0.326615), (2, 0.06755132), (8, 0.18391013)]
Speech 112 - Topic Distribution: [(2, 0.052322544), (3, 0.7436535), (13, 0.08148757), (16, 0.119958155)]
Speech 113 - Topic Distribution: [(2, 0.14654063), (7, 0.06237659), (9, 0.11439418), (12, 0.67638487)]
Speech 114 - Topic Distribution: [(2, 0.53292805), (6, 0.23015435), (12, 0.23050511)]
Speech 115 - Topic Distribution: [(13, 0.528216), (16, 0.47114965)]
Speech 116 - Topic Distribution: [(2, 0.4212966), (9, 0.54720217), (19, 0.031095061)]
Speech 117 - Topic Distribution: [(1, 0.22089326), (2, 0.32800883), (12, 0.3402221), (15, 0.110041834)]
Speech 118 - Topic Distribution: [(2, 0.4507096), (9, 0.45210934), (12, 0.09680761)]
Speech 119 - Topic Distribution: [(0, 0.038927525), (1, 0.058384616), (2, 0.6237433), (6, 0.27717802)]
Speech 120 - Topic Distribution: [(1, 0.45454732), (2, 0.3251483), (15, 0.21956204)]
Speech 121 - Topic Distribution: [(1, 0.38012293), (3, 0.18848571), (6, 0.019496532), (7, 0.0762647), (9, 0.12577236), (11, 0.16982578), (12, 0.03974646)]
Speech 122 - Topic Distribution: [(3, 0.050254244), (13, 0.8788527), (16, 0.07060132)]
Speech 123 - Topic Distribution: [(1, 0.047301985), (2, 0.34058553), (8, 0.05803664), (9, 0.02135097), (15, 0.2454872), (17, 0.16031696), (19, 0.11849228)]
Speech 124 - Topic Distribution: [(0, 0.050793), (1, 0.10291158), (2, 0.6926341), (3, 0.014307437), (6, 0.107320964), (16, 0.010510772), (19, 0.020918472)]
Speech 125 - Topic Distribution: [(7, 0.23313119), (13, 0.7232043), (16, 0.04332436)]
Speech 126 - Topic Distribution: [(1, 0.22293319), (2, 0.22986582), (8, 0.29138488), (15, 0.24279293)]
Speech 127 - Topic Distribution: [(0, 0.15149112), (1, 0.1708068), (2, 0.12534861), (6, 0.38151357), (8, 0.030263249), (15, 0.13989082)]
Speech 128 - Topic Distribution: [(2, 0.551538), (8, 0.030176528), (9, 0.21091504), (12, 0.19812472)]
Speech 129 - Topic Distribution: [(1, 0.09443055), (13, 0.11861913), (16, 0.77557015)]
Speech 130 - Topic Distribution: [(1, 0.17326137), (2, 0.8040986), (15, 0.0152957905)]
Speech 131 - Topic Distribution: [(0, 0.012367863), (1, 0.4069993), (2, 0.16242227), (3, 0.09902075), (7, 0.04838811), (12, 0.27040914)]
Speech 132 - Topic Distribution: [(2, 0.08121876), (3, 0.7530658), (6, 0.09457894), (13, 0.027439788), (16, 0.04283657)]
Speech 133 - Topic Distribution: [(1, 0.3805116), (2, 0.32931042), (6, 0.0120201735), (9, 0.19965176), (12, 0.076565064)]
Speech 134 - Topic Distribution: [(2, 0.6920068), (9, 0.18525651), (12, 0.11686927)]
Speech 135 - Topic Distribution: [(1, 0.21594128), (2, 0.5976665), (9, 0.021008361), (15, 0.16344142)]
Speech 136 - Topic Distribution: [(1, 0.17531271), (3, 0.82397103)]
Speech 137 - Topic Distribution: [(2, 0.1464716), (7, 0.014269728), (9, 0.063061364), (12, 0.7757719)]
Speech 138 - Topic Distribution: [(2, 0.3746213), (9, 0.32444993), (12, 0.30063632)]
Speech 139 - Topic Distribution: [(2, 0.48775333), (9, 0.12634195), (12, 0.3855162)]
Speech 140 - Topic Distribution: [(0, 0.9144668), (3, 0.043858726), (16, 0.033445634)]
Speech 141 - Topic Distribution: [(1, 0.27278057), (3, 0.7243496)]
Speech 142 - Topic Distribution: [(13, 0.76689655), (16, 0.23270154)]
Speech 143 - Topic Distribution: [(1, 0.08479207), (3, 0.9144897)]
Speech 144 - Topic Distribution: [(2, 0.30858672), (9, 0.45127454), (12, 0.23307453)]
Speech 145 - Topic Distribution: [(1, 0.25626805), (2, 0.51506895), (3, 0.03622563), (12, 0.19173227)]
Speech 146 - Topic Distribution: [(1, 0.57695156), (16, 0.4205871)]
Speech 147 - Topic Distribution: [(0, 0.4105417), (1, 0.11002858), (2, 0.30060446), (6, 0.10692348), (8, 0.01423145), (12, 0.046031456), (15, 0.011109635)]
Speech 148 - Topic Distribution: [(1, 0.13928899), (2, 0.79058516), (12, 0.06913806)]
Speech 149 - Topic Distribution: [(1, 0.5356676), (2, 0.25368688), (8, 0.016367713), (15, 0.04861106), (16, 0.14242622)]
Speech 150 - Topic Distribution: [(1, 0.8582255), (3, 0.13961422)]
Speech 151 - Topic Distribution: [(1, 0.3525696), (2, 0.31542847), (9, 0.32831544)]
Speech 152 - Topic Distribution: [(13, 0.7460353), (16, 0.2537218)]
Speech 153 - Topic Distribution: [(0, 0.016313726), (6, 0.101142064), (7, 0.42855564), (9, 0.04542385), (12, 0.40449646)]
Speech 154 - Topic Distribution: [(2, 0.019929912), (6, 0.9217725), (7, 0.05735028)]
Speech 155 - Topic Distribution: [(1, 0.23935983), (3, 0.75097936)]
Speech 156 - Topic Distribution: [(1, 0.45778683), (2, 0.19730675), (7, 0.09379994), (9, 0.04775612), (15, 0.20290276)]
Speech 157 - Topic Distribution: [(0, 0.21699859), (1, 0.27511147), (4, 0.016857468), (14, 0.013160996), (15, 0.46876752)]
Speech 158 - Topic Distribution: [(1, 0.9650264), (3, 0.034340054)]
Speech 159 - Topic Distribution: [(2, 0.25865167), (9, 0.5888544), (12, 0.15219814)]
Speech 160 - Topic Distribution: [(6, 0.14336565), (7, 0.59382594), (9, 0.061104935), (13, 0.19890453)]
Speech 161 - Topic Distribution: [(2, 0.6070974), (9, 0.3140562), (12, 0.07823135)]
Speech 162 - Topic Distribution: [(0, 0.02335892), (13, 0.34966055), (16, 0.6231206)]
Speech 163 - Topic Distribution: [(2, 0.49772438), (9, 0.32277647), (12, 0.17906675)]
Speech 164 - Topic Distribution: [(0, 0.017605944), (2, 0.35863003), (3, 0.014106726), (6, 0.3531811), (12, 0.24913175)]
Speech 165 - Topic Distribution: [(0, 0.03307548), (1, 0.34754202), (2, 0.27677715), (9, 0.08968611), (11, 0.016395355), (12, 0.23011646)]
Speech 166 - Topic Distribution: [(0, 0.08481417), (8, 0.29252818), (9, 0.030677045), (12, 0.5904973)]
Speech 167 - Topic Distribution: [(1, 0.013592313), (7, 0.012698616), (9, 0.6454331), (12, 0.29572234), (15, 0.022924159)]
Speech 168 - Topic Distribution: [(0, 0.04414977), (1, 0.08241646), (2, 0.15138821), (3, 0.3330957), (6, 0.21969695), (12, 0.078232), (15, 0.05433069), (16, 0.03601915)]
Speech 169 - Topic Distribution: [(2, 0.40664834), (9, 0.18716842), (12, 0.4054424)]
Speech 170 - Topic Distribution: [(13, 0.6608817), (16, 0.33859375)]
Speech 171 - Topic Distribution: [(1, 0.40507248), (3, 0.5918807)]
Speech 172 - Topic Distribution: [(1, 0.67881495), (3, 0.31936842)]
Speech 173 - Topic Distribution: [(1, 0.26042256), (2, 0.28358525), (8, 0.4274024), (15, 0.02674745)]
Speech 174 - Topic Distribution: [(1, 0.29532987), (3, 0.70406306)]
Speech 175 - Topic Distribution: [(3, 0.011755422), (7, 0.06822704), (9, 0.05601936), (13, 0.5447995), (16, 0.118514396), (19, 0.20034043)]
Speech 176 - Topic Distribution: [(1, 0.6654922), (3, 0.33311382)]
Speech 177 - Topic Distribution: [(1, 0.058436707), (2, 0.28776947), (8, 0.104929455), (9, 0.11594917), (15, 0.21597865), (17, 0.07816447), (19, 0.13842432)]
Speech 178 - Topic Distribution: [(0, 0.097331025), (1, 0.11783053), (2, 0.48043662), (3, 0.05037509), (6, 0.07157913), (12, 0.15430915), (19, 0.027608387)]
Speech 179 - Topic Distribution: [(1, 0.74983203), (3, 0.061455835), (6, 0.18509668)]
Speech 180 - Topic Distribution: [(2, 0.1026913), (7, 0.21778245), (9, 0.2653721), (12, 0.41223142)]
Speech 181 - Topic Distribution: [(3, 0.043632604), (6, 0.43710643), (13, 0.3746811), (16, 0.07699253), (19, 0.06201372)]
Speech 182 - Topic Distribution: [(2, 0.021581152), (9, 0.9440369), (12, 0.03404917)]
Speech 183 - Topic Distribution: [(1, 0.5038474), (2, 0.089334115), (8, 0.0512372), (15, 0.25457075), (16, 0.093424365)]
Speech 184 - Topic Distribution: [(6, 0.07792291), (12, 0.91353464)]
Speech 185 - Topic Distribution: [(2, 0.049879186), (3, 0.6071384), (13, 0.041550625), (16, 0.30010828)]
Speech 186 - Topic Distribution: [(1, 0.0116332695), (2, 0.6553122), (9, 0.3297314)]
Speech 187 - Topic Distribution: [(0, 0.06985124), (1, 0.27321455), (2, 0.30423668), (7, 0.020081965), (12, 0.33191797)]
Speech 188 - Topic Distribution: [(0, 0.048180617), (1, 0.36317813), (2, 0.013365208), (7, 0.30156958), (9, 0.26256523)]
Speech 189 - Topic Distribution: [(1, 0.6342497), (3, 0.35981527)]
Speech 190 - Topic Distribution: [(7, 0.03168469), (9, 0.06613563), (12, 0.90171987)]
Speech 191 - Topic Distribution: [(9, 0.21567339), (12, 0.7738928)]
Speech 192 - Topic Distribution: [(1, 0.050160456), (2, 0.09136247), (8, 0.011941022), (9, 0.14112812), (12, 0.7037075)]
Speech 193 - Topic Distribution: [(6, 0.2865841), (7, 0.2903382), (9, 0.123924844), (12, 0.29884678)]
Speech 194 - Topic Distribution: [(1, 0.18543808), (7, 0.10599146), (9, 0.14589097), (12, 0.562333)]
Speech 195 - Topic Distribution: [(1, 0.62098676), (3, 0.26280764), (6, 0.114849076)]
Speech 196 - Topic Distribution: [(2, 0.4056244), (9, 0.4323645), (12, 0.1616709)]
Speech 197 - Topic Distribution: [(1, 0.5276254), (2, 0.078886725), (6, 0.25830254), (8, 0.02490959), (16, 0.07270511), (18, 0.032727487)]
Speech 198 - Topic Distribution: [(1, 0.0968061), (2, 0.2560346), (3, 0.085357934), (6, 0.2689942), (12, 0.28251588)]
Speech 199 - Topic Distribution: [(2, 0.014267597), (9, 0.35885832), (12, 0.62615377)]
Speech 200 - Topic Distribution: [(1, 0.0950857), (2, 0.4029957), (3, 0.026907349), (12, 0.466568)]
Speech 201 - Topic Distribution: [(1, 0.2974362), (3, 0.70171577)]
Speech 202 - Topic Distribution: [(1, 0.105794504), (2, 0.1258677), (7, 0.020317433), (9, 0.13582923), (16, 0.6074856)]
Speech 203 - Topic Distribution: [(1, 0.5940118), (3, 0.016752094), (6, 0.24239156), (7, 0.14583461)]

In [6]:
# Print topics identified by LDA model
for topic_idx, topic in lda_model.print_topics():
    print(topic)
    print()

0.030*"financial" + 0.014*"risk" + 0.013*"bank" + 0.010*"banking" + 0.009*"market" + 0.008*"policy" + 0.008*"stability" + 0.008*"system" + 0.007*"macroprudential" + 0.007*"crisis"

0.015*"payment" + 0.013*"bank" + 0.009*"market" + 0.009*"european" + 0.009*"financial" + 0.007*"euro" + 0.007*"also" + 0.007*"ha" + 0.006*"would" + 0.006*"service"

0.022*"bank" + 0.021*"market" + 0.016*"central" + 0.013*"financial" + 0.011*"policy" + 0.011*"liquidity" + 0.010*"monetary" + 0.008*"money" + 0.008*"risk" + 0.008*"rate"

0.015*"financial" + 0.013*"policy" + 0.013*"euro" + 0.013*"area" + 0.011*"monetary" + 0.011*"bank" + 0.009*"market" + 0.009*"ha" + 0.009*"crisis" + 0.008*"price"

0.039*"die" + 0.035*"der" + 0.027*"und" + 0.012*"zu" + 0.011*"den" + 0.010*"ist" + 0.009*"von" + 0.009*"fã¼r" + 0.009*"da" + 0.009*"im"

0.063*"de" + 0.038*"la" + 0.019*"le" + 0.016*"en" + 0.011*"que" + 0.011*"et" + 0.009*"el" + 0.008*"los" + 0.007*"euro" + 0.006*"un"

0.019*"euro" + 0.015*"area" + 0.012*"country" + 0.011*"european" + 0.011*"ha" + 0.010*"economic" + 0.009*"policy" + 0.009*"market" + 0.008*"union" + 0.007*"growth"

0.018*"policy" + 0.017*"inflation" + 0.017*"rate" + 0.012*"monetary" + 0.010*"euro" + 0.010*"area" + 0.009*"bank" + 0.008*"ecb" + 0.007*"purchase" + 0.007*"ha"

0.017*"policy" + 0.016*"inflation" + 0.012*"monetary" + 0.011*"rate" + 0.011*"price" + 0.009*"euro" + 0.008*"growth" + 0.008*"ha" + 0.008*"economy" + 0.008*"area"

0.017*"risk" + 0.012*"bank" + 0.012*"climate" + 0.011*"policy" + 0.011*"financial" + 0.007*"central" + 0.007*"ecb" + 0.006*"change" + 0.006*"model" + 0.005*"monetary"

In [7]:
import pandas as pd

# Define the indices of the topics you are interested in
topics_of_interest = [0, 1, 3, 6, 7, 8]  # Adjust based on your topics of interest

# Create an empty list to store relevant speeches
relevant_speeches = []

# Iterate through each speech and filter based on topics of interest
for idx, speech in speeches_df.iterrows():
    topic_distribution = get_topic_distribution(speech['text'])
    # Check if any of the topics of interest have significant probability in the topic distribution
    relevant_topics = [topic for topic, prob in topic_distribution if topic in topics_of_interest and prob > 0.2]
    if relevant_topics:
        relevant_speeches.append(speech)

# Convert the list of relevant speeches into a DataFrame
relevant_speeches_df = pd.DataFrame(relevant_speeches)

# Print or do something else with the relevant speeches DataFrame
print(relevant_speeches_df)

      Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0       date  \
0                0          1971        2023 2006-01-13
2                2          1969        2021 2006-01-20
3                3          1968        2020 2006-02-02
4                4          1967        2019 2006-02-06
5                5          1966        2018 2006-02-10
...            ...           ...         ...        ...
1488          1488             5           5 2023-11-21
1490          1490             3           3 2023-11-27
1491          1491             2           2 2023-11-30
1492          1492             1           1 2023-12-04
1493          1493             0           0 2023-12-07

                            speakers  \
0                Jean-Claude Trichet
2                Jean-Claude Trichet
3     JosÃ© Manuel GonzÃ¡lez-PÃ¡ramo
4                Jean-Claude Trichet
5                    Lucas Papademos
...                              ...
1488               Christine Lagarde
1490               Christine Lagarde
1491               Christine Lagarde
1492               Christine Lagarde
1493                  Frank Elderson

                                                  title  \
0     The process of European financial integration:...
2     Growth performance, labour productivity and st...
3     Some observations on the measurement of econom...
4     Monetary Policy and Economic Prospects in the ...
5     The euro area economy and emerging Asia - curr...
...                                                 ...
1488  Monetary policy in the euro area: attentive an...
1490  Hearing of the Committee on Economic and Monet...
1491  Welcome address at the fifth ECB Forum on Bank...
1492                      Governance at a turning point
1493  Powers, ability and willingness to act â€“ the...

                                               subtitle  \
0     Speech by Jean-Claude Trichet, President of th...
2     Speech by Jean-Claude Trichet, President of th...
3     Speech by JosÃ© Manuel GonzÃ¡lez-PÃ¡ramo, Memb...
4     Speech by Jean-Claude Trichet, President of th...
5     Speech by Lucas Papademos, Vice-President of t...
...                                                 ...
1488  Speech by Christine Lagarde, President of the ...
1490  Speech by Christine Lagarde, President of the ...
1491  Speech by Christine Lagarde, President of the ...
1492  Speech by Christine Lagarde, President of the ...
1493  Speech by Frank Elderson, Member of the Execut...

                                                   text sentiment vader  \
0     process european financial integration stand s...        positive
2     growth performance labour productivity structu...        positive
3     observation measurement economic phenomenon sp...        positive
4     monetary policy economic prospect euro area sp...        positive
5     euro area economy emerging asia current issue ...        positive
...                                                 ...             ...
1488  monetary policy euro area attentive focused sp...        positive
1490  hearing committee economic monetary affair eur...        positive
1491  welcome address fifth ecb forum banking superv...        positive
1492  governance turning point speech christine laga...        positive
1493  power ability willingness act mainstay effecti...        positive

      vader_sentiment  Polarity_Score  \
0            0.456111        0.590361
2            0.330985        0.024096
3            0.420023        0.181818
4            0.597796        0.049645
5            0.609319        0.120000
...               ...             ...
1488         0.001633       -0.333333
1490         0.122029       -0.123288
1491         0.197858       -0.131579
1492         0.411013       -0.127753
1493         0.117744       -0.329480

                                         processed_text
0     [process, european, financial, integration, st...
2     [growth, performance, labour, productivity, st...
3     [observation, measurement, economic, phenomeno...
4     [monetary, policy, economic, prospect, euro, a...
5     [euro, area, economy, emerging, asia, current,...
...                                                 ...
1488  [monetary, policy, euro, area, attentive, focu...
1490  [hearing, committee, economic, monetary, affai...
1491  [welcome, address, fifth, ecb, forum, banking,...
1492  [governance, turning, point, speech, christine...
1493  [power, ability, willingness, act, mainstay, e...

[1371 rows x 12 columns]

In [8]:
relevant_speeches_df.to_excel('ECBdatasentimentfinal4ln.xlsx', index=False)